/- Generated by scripts/s31_formal.py from reviewed coverage.json. -/
import S31.Gadgets

#check S31.Field.inverse_sound_complete
#check S31.Functional.arrayCode_accepts
#check S31.Functional.u16_value_valid_iff
#check S31.Functional.u16_vector_select_bounded
#check S31.Functional.u16_vector_select_iff
#check S31.Functional.u16_wire_vector_matches_source
#check S31.Functional.u16_wire_vector_select_bounded
#check S31.Functional.u16_wire_vector_select_iff
#check S31.Functional.u16_wire_vector_value_valid
#check S31.Gadgets.Air.BitRows.acceptsBit_iff
#check S31.Gadgets.Air.BooleanRows.and_iff
#check S31.Gadgets.Air.BooleanRows.not_iff
#check S31.Gadgets.Air.BooleanRows.or_iff
#check S31.Gadgets.Air.BooleanRows.select_iff
#check S31.Gadgets.Air.BooleanRows.xor_iff
#check S31.Gadgets.Air.FunctionalBridge.array_graph_iff_air_row
#check S31.Gadgets.Air.GateLookup.addressed_row_sound
#check S31.Gadgets.Air.InverseRows.packedInverseRows_iff
#check S31.Gadgets.Air.InverseRows.zero_active_lane_rejected
#check S31.Gadgets.Air.MixRows.mix4Rows_iff_applyStep
#check S31.Gadgets.Air.Qm31Ops.row_iff_normalized_node
#check S31.Gadgets.Air.SelectRows.untrusted_selector_self_product_iff
#check S31.Gadgets.Air.SelectRows.untrusted_self_product_select_iff_evaluateNode
#check S31.Gadgets.Air.SimdChunks.partial_row_iff_normalized_node
#check S31.Gadgets.Air.SumRows.compiledSumLanesRows_iff_evaluateNode
#check S31.Gadgets.Air.UnpackRows.packedUnpack_iff
#check S31.Gadgets.Air.ZeroRows.acceptsZeroTest_iff
#check S31.Gadgets.Air.ZeroRows.base_zero_test_iff_evaluateNode
#check S31.Gadgets.Arithmetic.comparison_sound_complete
#check S31.Gadgets.Arithmetic.signed_add_sound_complete
#check S31.Gadgets.Arithmetic.signed_sub_sound_complete
#check S31.Gadgets.Arithmetic.twos_emod
#check S31.Gadgets.Bindings.array_concat_wires
#check S31.Gadgets.Bindings.array_get_wire
#check S31.Gadgets.Bindings.array_slice_wires
#check S31.Gadgets.Bindings.cast_wire_identity
#check S31.Gadgets.Bindings.constant_wires
#check S31.Gadgets.Bitcoin.division_sound_complete
#check S31.Gadgets.Bitcoin.exponent_sound_complete
#check S31.Gadgets.Bitcoin.target_byte_placement
#check S31.Gadgets.Bitcoin.work_sound_complete
#check S31.Gadgets.CompactTarget.target_sound_complete
#check S31.Gadgets.Hash.poseidon_leaf_sound_complete
#check S31.Gadgets.Hash.poseidon_pair_sound_complete
#check S31.Gadgets.Hash.sbox_sound_complete
#check S31.Gadgets.HashEncoding.blake_hash_sound_complete
#check S31.Gadgets.HashEncoding.header_hash_sound_complete
#check S31.Gadgets.HashEncoding.sha_hash_sound_complete
#check S31.Gadgets.IntegerMultiply.column_complete
#check S31.Gadgets.IntegerMultiply.column_sound
#check S31.Gadgets.IntegerMultiply.full_product_sound
#check S31.Gadgets.IntegerMultiply.signed_checked_complete
#check S31.Gadgets.IntegerMultiply.signed_checked_sound
#check S31.Gadgets.IntegerMultiply.split_high_byte_sound
#check S31.Gadgets.IntegerMultiply.unsigned_checked_complete
#check S31.Gadgets.IntegerMultiply.unsigned_checked_sound
#check S31.Gadgets.IntegerMultiply.wrapping_product_sound
#check S31.Gadgets.Packed.add_sound_complete
#check S31.Gadgets.Packed.dual_literal
#check S31.Gadgets.Packed.inverse_sound_complete
#check S31.Gadgets.Packed.mask_active_lanes
#check S31.Gadgets.Packed.mix4_broadcast
#check S31.Gadgets.Packed.pointwise_sound_complete
#check S31.Gadgets.Packed.scalar_mul
#check S31.Gadgets.Packed.sum_projection
#check S31.Gadgets.Packed.unpack_coordinate
#check S31.Gadgets.Packing.bits_sound_complete
#check S31.Gadgets.Packing.byte_pair_m31_sound_complete
#check S31.Gadgets.Packing.byte_pair_sound_complete
#check S31.Gadgets.Packing.bytes_le_roundtrip
#check S31.Gadgets.Packing.digest_reduction_sound_complete
#check S31.Gadgets.Packing.integer_layout
#check S31.Gadgets.Packing.top_limb_sign
#check S31.Gadgets.Radix.add_chain_checked_sound_complete
#check S31.Gadgets.Radix.add_chain_wrapping_sound_complete
#check S31.Gadgets.Radix.byte_sound_complete
#check S31.Gadgets.Radix.sub_chain_checked_sound_complete
#check S31.Gadgets.Radix.sub_chain_comparison
#check S31.Gadgets.Radix.sub_chain_wrapping_sound_complete
#check S31.Gadgets.Schoolbook.product_coefficients_bounded
#check S31.Gadgets.Schoolbook.schoolbook_product_sound_complete
#check S31.Gadgets.Sequence.pointwise_sound_complete
#check S31.Gadgets.Sequence.repeat_sound_complete
#check S31.Gadgets.Sequence.step_sound_complete
#check S31.Gadgets.Sequence.sum_sound_complete
#check S31.Gadgets.Signed.le_sound_complete
#check S31.Gadgets.Signed.sign_sound_complete
#check S31.Gadgets.Signed.signed_le
#check S31.Gadgets.Word.primitive_sound_complete
#check S31.Gadgets.add_sound_complete
#check S31.Gadgets.and_sound_complete
#check S31.Gadgets.bit_sound_complete
#check S31.Gadgets.boolean_select_sound_complete
#check S31.Gadgets.inverse_sound_complete
#check S31.Gadgets.is_zero_sound_complete
#check S31.Gadgets.mul_sound_complete
#check S31.Gadgets.not_sound_complete
#check S31.Gadgets.or_sound_complete
#check S31.Gadgets.select_sound_complete
#check S31.Gadgets.xor_sound_complete
#check S31.Gadgets.zero_anchor_sound_complete

#check S31.Bitcoin.blockWork
#check S31.Bitcoin.genesis
#check S31.Bitcoin.headerTarget
#check S31.Blake2s.hash
#check S31.Field.inverse
#check S31.Integers.evaluate
#check S31.Integers.u256
#check S31.Poseidon2.leaf
#check S31.Poseidon2.pair
#check S31.Sha256.header
#check S31.evaluateNode
#check S31.repeatBody

namespace S31.Evidence

def operationCoverage : List (Op × List String) := [
  (.constant, ["S31.Gadgets.Bindings.constant_wires"]),
  (.cast_m31, ["S31.Gadgets.Bindings.cast_wire_identity"]),
  (.add, ["S31.Gadgets.add_sound_complete", "S31.Gadgets.Packed.add_sound_complete", "S31.Gadgets.Air.Qm31Ops.row_iff_normalized_node", "S31.Gadgets.Air.SimdChunks.partial_row_iff_normalized_node", "S31.Gadgets.Air.FunctionalBridge.array_graph_iff_air_row", "S31.Gadgets.Air.GateLookup.addressed_row_sound", "S31.Gadgets.Sequence.pointwise_sound_complete", "S31.Functional.arrayCode_accepts"]),
  (.mul, ["S31.Gadgets.mul_sound_complete", "S31.Gadgets.Packed.pointwise_sound_complete", "S31.Gadgets.Air.Qm31Ops.row_iff_normalized_node", "S31.Gadgets.Air.SimdChunks.partial_row_iff_normalized_node", "S31.Gadgets.Air.FunctionalBridge.array_graph_iff_air_row", "S31.Gadgets.Air.GateLookup.addressed_row_sound", "S31.Gadgets.Sequence.pointwise_sound_complete", "S31.Functional.arrayCode_accepts"]),
  (.add_const, ["S31.Gadgets.add_sound_complete", "S31.Gadgets.Sequence.step_sound_complete"]),
  (.mul_const, ["S31.Gadgets.mul_sound_complete", "S31.Gadgets.Packed.scalar_mul", "S31.Gadgets.Sequence.step_sound_complete"]),
  (.repeat, ["S31.Gadgets.Sequence.repeat_sound_complete", "S31.Gadgets.Sequence.step_sound_complete", "S31.Gadgets.Packed.mix4_broadcast", "S31.Gadgets.Air.MixRows.mix4Rows_iff_applyStep"]),
  (.hash_blake2s, ["S31.Gadgets.HashEncoding.blake_hash_sound_complete", "S31.Gadgets.Word.primitive_sound_complete", "S31.Gadgets.Packing.digest_reduction_sound_complete"]),
  (.hash_blake2s_leaf, ["S31.Gadgets.HashEncoding.blake_hash_sound_complete", "S31.Gadgets.Word.primitive_sound_complete", "S31.Gadgets.Packing.digest_reduction_sound_complete"]),
  (.hash_blake2s_pair, ["S31.Gadgets.HashEncoding.blake_hash_sound_complete", "S31.Gadgets.Bindings.array_concat_wires"]),
  (.select, ["S31.Gadgets.bit_sound_complete", "S31.Gadgets.select_sound_complete", "S31.Gadgets.Sequence.pointwise_sound_complete", "S31.Functional.u16_vector_select_iff", "S31.Functional.u16_vector_select_bounded", "S31.Functional.u16_wire_vector_select_iff", "S31.Functional.u16_wire_vector_select_bounded", "S31.Functional.u16_value_valid_iff", "S31.Functional.u16_wire_vector_value_valid", "S31.Functional.u16_wire_vector_matches_source", "S31.Gadgets.Air.SelectRows.untrusted_selector_self_product_iff", "S31.Gadgets.Air.SelectRows.untrusted_self_product_select_iff_evaluateNode", "S31.Gadgets.Air.BitRows.acceptsBit_iff", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.hash_poseidon2_leaf, ["S31.Gadgets.Hash.poseidon_leaf_sound_complete", "S31.Gadgets.Hash.sbox_sound_complete"]),
  (.hash_poseidon2_pair, ["S31.Gadgets.Hash.poseidon_pair_sound_complete", "S31.Gadgets.Hash.sbox_sound_complete"]),
  (.sum_lanes, ["S31.Gadgets.Sequence.sum_sound_complete", "S31.Gadgets.Packed.mask_active_lanes", "S31.Gadgets.Packed.sum_projection", "S31.Gadgets.Packed.dual_literal", "S31.Gadgets.Air.SumRows.compiledSumLanesRows_iff_evaluateNode"]),
  (.u256_add, ["S31.Gadgets.Radix.add_chain_wrapping_sound_complete"]),
  (.u256_le, ["S31.Gadgets.Arithmetic.comparison_sound_complete", "S31.Gadgets.Radix.sub_chain_comparison", "S31.Gadgets.not_sound_complete"]),
  (.u256_add_checked, ["S31.Gadgets.Radix.add_chain_checked_sound_complete"]),
  (.hash_sha256d_header, ["S31.Gadgets.HashEncoding.header_hash_sound_complete", "S31.Gadgets.HashEncoding.sha_hash_sound_complete", "S31.Gadgets.Packing.byte_pair_m31_sound_complete"]),
  (.bitcoin_target_mainnet, ["S31.Gadgets.CompactTarget.target_sound_complete", "S31.Gadgets.Bitcoin.target_byte_placement", "S31.Gadgets.Bitcoin.exponent_sound_complete", "S31.Gadgets.Packing.bits_sound_complete", "S31.Gadgets.Packing.byte_pair_sound_complete"]),
  (.bitcoin_prev_hash, ["S31.Gadgets.Bindings.array_slice_wires"]),
  (.bitcoin_header_bits, ["S31.Gadgets.Bindings.array_slice_wires"]),
  (.bitcoin_genesis_hash_mainnet, ["S31.Gadgets.Bindings.constant_wires", "S31.Gadgets.Packing.bytes_le_roundtrip"]),
  (.bitcoin_header_time, ["S31.Gadgets.Bindings.array_slice_wires"]),
  (.u32_lt, ["S31.Gadgets.Arithmetic.comparison_sound_complete", "S31.Gadgets.Radix.sub_chain_comparison"]),
  (.inv, ["S31.Gadgets.Packed.inverse_sound_complete", "S31.Field.inverse_sound_complete", "S31.Gadgets.inverse_sound_complete", "S31.Gadgets.Air.InverseRows.packedInverseRows_iff", "S31.Gadgets.Air.InverseRows.zero_active_lane_rejected"]),
  (.is_zero, ["S31.Gadgets.is_zero_sound_complete", "S31.Gadgets.zero_anchor_sound_complete", "S31.Gadgets.Air.ZeroRows.acceptsZeroTest_iff", "S31.Gadgets.Air.ZeroRows.base_zero_test_iff_evaluateNode", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.u256_sub, ["S31.Gadgets.Radix.sub_chain_wrapping_sound_complete"]),
  (.u256_sub_checked, ["S31.Gadgets.Radix.sub_chain_checked_sound_complete"]),
  (.array_get, ["S31.Gadgets.Bindings.array_get_wire", "S31.Gadgets.Packed.unpack_coordinate", "S31.Functional.arrayCode_accepts"]),
  (.array_concat, ["S31.Gadgets.Bindings.array_concat_wires", "S31.Functional.arrayCode_accepts"]),
  (.array_slice, ["S31.Gadgets.Bindings.array_slice_wires", "S31.Functional.arrayCode_accepts"]),
  (.bool_not, ["S31.Gadgets.bit_sound_complete", "S31.Gadgets.not_sound_complete", "S31.Gadgets.Air.BooleanRows.not_iff", "S31.Gadgets.Air.BitRows.acceptsBit_iff", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.bool_and, ["S31.Gadgets.bit_sound_complete", "S31.Gadgets.and_sound_complete", "S31.Gadgets.Air.BooleanRows.and_iff", "S31.Gadgets.Air.BitRows.acceptsBit_iff", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.bool_or, ["S31.Gadgets.bit_sound_complete", "S31.Gadgets.or_sound_complete", "S31.Gadgets.Air.BooleanRows.or_iff", "S31.Gadgets.Air.BitRows.acceptsBit_iff", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.bool_xor, ["S31.Gadgets.bit_sound_complete", "S31.Gadgets.xor_sound_complete", "S31.Gadgets.Air.BooleanRows.xor_iff", "S31.Gadgets.Air.BitRows.acceptsBit_iff", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.bool_select, ["S31.Gadgets.bit_sound_complete", "S31.Gadgets.boolean_select_sound_complete", "S31.Gadgets.Air.BooleanRows.select_iff", "S31.Gadgets.Air.BitRows.acceptsBit_iff", "S31.Gadgets.Air.UnpackRows.packedUnpack_iff"]),
  (.bitcoin_block_work, ["S31.Gadgets.Bitcoin.work_sound_complete", "S31.Gadgets.Bitcoin.division_sound_complete", "S31.Gadgets.Schoolbook.schoolbook_product_sound_complete", "S31.Gadgets.Schoolbook.product_coefficients_bounded", "S31.Gadgets.Arithmetic.comparison_sound_complete"]),
  (.int_view, ["S31.Gadgets.Bindings.cast_wire_identity", "S31.Gadgets.Radix.byte_sound_complete", "S31.Gadgets.Packing.integer_layout"]),
  (.int_add_checked, ["S31.Gadgets.Radix.add_chain_checked_sound_complete", "S31.Gadgets.Arithmetic.signed_add_sound_complete", "S31.Gadgets.Signed.sign_sound_complete", "S31.Gadgets.Packing.top_limb_sign"]),
  (.int_add_wrapping, ["S31.Gadgets.Radix.add_chain_wrapping_sound_complete", "S31.Gadgets.Arithmetic.twos_emod", "S31.Gadgets.Packing.integer_layout"]),
  (.int_sub_checked, ["S31.Gadgets.Radix.sub_chain_checked_sound_complete", "S31.Gadgets.Arithmetic.signed_sub_sound_complete", "S31.Gadgets.Signed.sign_sound_complete", "S31.Gadgets.Packing.top_limb_sign"]),
  (.int_sub_wrapping, ["S31.Gadgets.Radix.sub_chain_wrapping_sound_complete", "S31.Gadgets.Arithmetic.twos_emod", "S31.Gadgets.Packing.integer_layout"]),
  (.int_le, ["S31.Gadgets.Arithmetic.comparison_sound_complete", "S31.Gadgets.Signed.signed_le", "S31.Gadgets.Signed.le_sound_complete", "S31.Gadgets.Signed.sign_sound_complete"]),
  (.int_mul_wrapping, ["S31.Gadgets.IntegerMultiply.column_sound", "S31.Gadgets.IntegerMultiply.column_complete", "S31.Gadgets.IntegerMultiply.split_high_byte_sound", "S31.Gadgets.IntegerMultiply.wrapping_product_sound", "S31.Gadgets.Radix.byte_sound_complete"]),
  (.int_mul_checked, ["S31.Gadgets.IntegerMultiply.column_sound", "S31.Gadgets.IntegerMultiply.column_complete", "S31.Gadgets.IntegerMultiply.full_product_sound", "S31.Gadgets.IntegerMultiply.unsigned_checked_sound", "S31.Gadgets.IntegerMultiply.unsigned_checked_complete", "S31.Gadgets.IntegerMultiply.signed_checked_sound", "S31.Gadgets.IntegerMultiply.signed_checked_complete", "S31.Gadgets.Signed.sign_sound_complete"])]

theorem operation_inventory_exact : operationCoverage.map Prod.fst = allOps := rfl

theorem operation_inventory_complete (op : Op) :
    op ∈ operationCoverage.map Prod.fst := by cases op <;> simp [operationCoverage]

theorem operation_inventory_size : operationCoverage.length = 45 := rfl

end S31.Evidence
