import S31.Gadgets.Arithmetic
import S31.Gadgets.IntegerMultiply
import S31.Gadgets.IntegerCast
import S31.Gadgets.IntegerBits
import S31.Gadgets.IntegerShift
import S31.Gadgets.IntegerDivision
import S31.Gadgets.Air.Qm31Ops
import S31.Gadgets.Air.PackRows
import S31.Gadgets.Air.NativeQm31AirProof
import S31.Gadgets.Air.NativeLogUpAirProof
import S31.Gadgets.Air.NativeGateRawSoundness
import S31.Gadgets.Air.NativeEqRawSoundness
import S31.Gadgets.Air.NativeLogUpBatchesProof
import S31.Gadgets.Air.CompositionFold
import S31.Gadgets.Functional.TextSquare4Proof
import S31.Gadgets.Functional.TextSquare4Air
import S31.Gadgets.Functional.TextSquare4Statement
import S31.Gadgets.Functional.TextSquare4CompilerChain
import S31.Gadgets.Functional.TextSquare4NativeProof
import S31.Gadgets.Functional.TextSquare4NativeBoundary
import S31.Gadgets.Functional.TextSquare4GateJoin
import S31.Gadgets.Functional.TextSquare4ChallengeJoin
import S31.Gadgets.Functional.TextSquare4TraceRows
import S31.Gadgets.Functional.TextSquare4TraceValues
import S31.Gadgets.Functional.TextSquare4ProducerRoster
import S31.Gadgets.Functional.TextSquare4Witness
import S31.Gadgets.Functional.TextSquare4WitnessAll
import S31.Gadgets.Functional.TextSquare4RawSoundness
import S31.Gadgets.Air.QuadField
import S31.Gadgets.Air.SimdChunks
import S31.Gadgets.Air.FunctionalBridge
import S31.Gadgets.Air.AffineChipBoundary
import S31.Gadgets.Air.GenericChipBoundary
import S31.Gadgets.Air.IndexedChipPath
import S31.Gadgets.Air.RawChipIndexCoverage
import S31.Gadgets.Air.TaggedPairBridgeRows
import S31.Gadgets.Air.TaggedPairChallenge
import S31.Gadgets.Air.TaggedPairAirClosure
import S31.Gadgets.Air.TaggedPairSourceCorrespondence
import S31.Gadgets.Air.TaggedPairSourceComposition
import S31.Gadgets.Air.TaggedPairEventProjection
import S31.Gadgets.Air.PrivateBridgeChallenge
import S31.Gadgets.Air.PrivateBridgeChallengeMany
import S31.Gadgets.Air.SelectRows
import S31.Gadgets.Air.BooleanRows
import S31.Gadgets.Air.BitRows
import S31.Gadgets.Air.ZeroRows
import S31.Gadgets.Air.InverseRows
import S31.Gadgets.Air.UnpackRows
import S31.Gadgets.Air.SumRows
import S31.Gadgets.Air.MixRows
import S31.Gadgets.Air.GateLookup
import S31.Gadgets.Air.GateWireMap
import S31.Gadgets.Air.GateTraceValues
import S31.Gadgets.Air.GateProducerRoster
import S31.Gadgets.Air.GateChallenge
import S31.Gadgets.Air.LogUpNumerator
import S31.Gadgets.Air.LogUpCount
import S31.Gadgets.Air.GateLogUpBridge
import S31.Gadgets.Air.GateLocalCounts
import S31.Gadgets.Air.GateChallengePairs
import S31.Gadgets.Air.GateAddressCounts
import S31.Gadgets.Air.GateCounter
import S31.Gadgets.Air.LogUpInteraction
import S31.Gadgets.Air.Qm31GateInteraction
import S31.Gadgets.Air.EqGateInteraction
import S31.Gadgets.Air.NativeEqRosterProof
import S31.Gadgets.Air.GateContributions
import S31.Gadgets.Air.NativeGateRosterProof
import S31.Gadgets.Air.GateChallengeClosure
import S31.Gadgets.Air.GateAirChallengeSoundness
import S31.Gadgets.Air.GateAirRawSoundness
import S31.Gadgets.Air.GateEqRawSoundness
import S31.Gadgets.Air.GateCounterCircuit
import S31.Gadgets.Air.GateUseTraversal
import S31.Gadgets.Air.PermutationScratch
import S31.Gadgets.Air.PermutationRows
import S31.Gadgets.Air.GateProducerCheck
import S31.Gadgets.Air.GateFinal
import S31.Gadgets.Air.EqRows
import S31.Gadgets.Bindings
import S31.Gadgets.BuilderValidity
import S31.Gadgets.CompactTarget
import S31.Gadgets.HashEncoding
import S31.Gadgets.HashBuilder
import S31.Gadgets.Functional.Graph
import S31.Gadgets.Functional.Outputs
import S31.Gadgets.Functional.Arrays
import S31.Gadgets.Functional.ArrayNodes
import S31.Gadgets.Functional.ArithmeticNodes
import S31.Gadgets.Functional.CompilerCorrespondence
import S31.Gadgets.Functional.SSACertificate
import S31.Gadgets.Functional.SSAEmitterProof
import S31.Gadgets.Functional.SSANamedProgram
import S31.Gadgets.Functional.SSANamedExecution
import S31.Gadgets.Functional.SSANamedPublicClaim
import S31.Gadgets.Functional.SSAAirRows
import S31.Gadgets.Functional.SSAConcreteGateSchedule
import S31.Gadgets.Functional.SSAConcreteGateLookup
import S31.Gadgets.Functional.SSANativeTopologyCheck
import S31.Gadgets.Functional.SSAGeneralNamedTopology
import S31.Gadgets.Functional.SSALocalPipeline
import S31.Gadgets.Functional.GeneratedDirectGateBridge
import S31.Gadgets.Functional.MathLibrary
import S31.Gadgets.Functional.WorkedQuadratic
import S31.Gadgets.Functional.CurriedApplication
import S31.Gadgets.Functional.NamedFunctionValue
import S31.Gadgets.Functional.HigherOrderRoutes
import S31.Gadgets.Functional.PowerChains
import S31.Gadgets.Functional.TupleValues
import S31.Gadgets.Functional.RecordValues
import S31.Gadgets.Functional.RecordBoundary
import S31.Gadgets.Functional.StaticRecurrence
import S31.Gadgets.Functional.WorkedMix4
import S31.Gadgets.Functional.Assertions
import S31.Gadgets.Functional.Conditional
import S31.Gadgets.Functional.ArrayConditional
import S31.Gadgets.Functional.Effects
import S31.Gadgets.U16Selection
import S31.Gadgets.Packed

/-! Local constraint relations, with arbitrary-witness soundness and honest
witness completeness. All range and representation premises are explicit. -/
