-- Generated by scripts/export_s31_direct_gate_bridge.py from a checked package.
-- Source SHA-256: 2555767fb91b626f6ad959eb87bb2a83626f1aaacab3ad63179d966eeedfd1f6
import S31.Gadgets.Functional.SSADirectGateBridge
import S31.Gadgets.Functional.SSAAirRows

set_option maxRecDepth 4096

namespace S31.Functional.GeneratedDirectGateBridge

open S31.Functional.SSACertificate
open S31.Functional.SSADirectGateBridge
open S31.Functional.SSAAirRows

def sourceBytes : List Nat := [
    47, 47, 32, 70, 105, 114, 115, 116, 45, 111, 114, 100, 101, 114, 32, 114,
    101, 102, 101, 114, 101, 110, 99, 101, 32, 102, 111, 114, 32, 116, 104, 101,
    32, 104, 105, 103, 104, 101, 114, 45, 111, 114, 100, 101, 114, 32, 96, 102,
    117, 110, 99, 116, 105, 111, 110, 97, 108, 95, 115, 113, 117, 97, 114, 101,
    52, 46, 115, 51, 49, 96, 46, 10, 99, 105, 114, 99, 117, 105, 116, 32,
    102, 117, 110, 99, 116, 105, 111, 110, 97, 108, 95, 115, 113, 117, 97, 114,
    101, 52, 40, 112, 117, 98, 108, 105, 99, 32, 120, 58, 32, 91, 109, 51,
    49, 59, 32, 52, 93, 41, 32, 45, 62, 32, 112, 117, 98, 108, 105, 99,
    32, 91, 109, 51, 49, 59, 32, 52, 93, 32, 123, 10, 32, 32, 32, 32,
    108, 101, 116, 32, 111, 110, 99, 101, 32, 61, 32, 120, 32, 46, 42, 32,
    120, 59, 10, 32, 32, 32, 32, 108, 101, 116, 32, 114, 101, 115, 117, 108,
    116, 32, 61, 32, 111, 110, 99, 101, 32, 46, 42, 32, 111, 110, 99, 101,
    59, 10, 32, 32, 32, 32, 114, 101, 115, 117, 108, 116, 10, 125, 10
  ]
def sourceSha256 : String := "2555767fb91b626f6ad959eb87bb2a83626f1aaacab3ad63179d966eeedfd1f6"

def source : Source 1 :=
  (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨0, by decide⟩)))

def certificate : Certificate :=
  { instructions := [
      { id := 1, lhs := 0, rhs := 0, multiply := true },
      { id := 2, lhs := 1, rhs := 1, multiply := true }],
    output := 2 }

def observedRows : List NativeSourceRow :=
  [
    { circuitRow := 6, traceRow := 502, multiply := true, in0 := 22, in1 := 22, out := 23 },
    { circuitRow := 7, traceRow := 503, multiply := true, in0 := 23, in1 := 23, out := 24 }
  ]

def observedAddRows : Nat := 474
def observedGateRows : Nat := 512
def observedVariables : Nat := 512

theorem source_byte_count : sourceBytes.length = 207 := by decide
theorem source_digest_length : sourceSha256.length = 64 := by decide
theorem source_ssa_checked : check source certificate = some () := by decide
theorem deterministic_emitter_matches : compile source = certificate := by decide
theorem source_native_rows_match :
    observedRows = expectedRows certificate observedAddRows := by decide
theorem complete_native_shape :
    observedGateRows = 512 ∧ observedVariables = 512 := by decide

def changedSource : Source 1 :=
  (.letValue (.add (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨0, by decide⟩)))

def changedOpcode : Certificate :=
  { instructions := [
      { id := 1, lhs := 0, rhs := 0, multiply := false },
      { id := 2, lhs := 1, rhs := 1, multiply := true }],
    output := 2 }

def changedAddressRows : List NativeSourceRow :=
  [
    { circuitRow := 6, traceRow := 502, multiply := true, in0 := 22, in1 := 23, out := 23 },
    { circuitRow := 7, traceRow := 503, multiply := true, in0 := 23, in1 := 23, out := 24 }
  ]

theorem changed_source_rejected : check changedSource certificate = none := by decide
theorem changed_opcode_rejected : check source changedOpcode = none := by decide
theorem changed_address_rejected :
    changedAddressRows ≠ expectedRows certificate observedAddRows := by decide

/-- Source semantics for every four-lane input follow from the concrete
certificate check. The native-row premise remains a package-checker output,
and lookup/PCS soundness remains outside this theorem. -/
theorem checked_instance_sound (input : Lanes) :
    executeNormalized certificate input =
      some (source.value (fun _ => input)) :=
  (checked_rows_source_sound source certificate input observedRows
    observedAddRows source_ssa_checked source_native_rows_match).2

/-- Any complete accepted local arithmetic-row trace for these exact source
instructions has the source result, provided the row operands are the values
authenticated at their addressed prior wires. This does not discharge that
lookup premise or establish PCS binding of the observed row artifact. -/
theorem checked_instance_air_claim (input claimed : Lanes)
    (final : List Lanes)
    (hrows : AcceptsTrace [input] certificate.instructions final)
    (hclaim : final[certificate.output]? = some claimed) :
    observedRows = expectedRows certificate observedAddRows ∧
      claimed = source.value (fun _ => input) := by
  have hcompiled : AcceptsTrace [input] (compile source).instructions final := by
    simpa [deterministic_emitter_matches] using hrows
  have houtput : final[(compile source).output]? = some claimed := by
    simpa [deterministic_emitter_matches] using hclaim
  exact ⟨source_native_rows_match,
    compiled_source_air_sound source input claimed final hcompiled houtput⟩

end S31.Functional.GeneratedDirectGateBridge
