-- Generated by scripts/export_s31_direct_gate_bridge.py from a checked package.
-- Source SHA-256: d382cee3a72ba2d22becf0c579580f97077e78e4cc7949f1e71c2800b42887be
import S31.Gadgets.Functional.SSADirectGateBridge
import S31.Gadgets.Functional.SSAAirRows
import S31.Gadgets.Functional.SSATextBytes
import S31.Gadgets.Functional.SSANormalizedBytes
import S31.Gadgets.Functional.SSAAirColumnCells
import S31.Gadgets.Functional.SSAOutputAirCells
import S31.Gadgets.Functional.SSAInputAirCells
import S31.Gadgets.Functional.SSAGeneralNamedExecution

set_option maxRecDepth 4096

namespace S31.Functional.GeneratedDirectGateMixedReturn

open S31.Functional.SSACertificate
open S31.Functional.SSADirectGateBridge
open S31.Functional.SSAAirRows
open S31.Functional.SSATextBytes
open S31.Functional.SSANormalizedBytes
open S31.Functional.SSAAirColumnCells
open S31.Functional.SSAOutputAirCells
open S31.Functional.SSAInputAirCells
open S31.Functional.SSAGeneralNamedTopology
open S31.Functional.SSAGeneralNamedExecution
open S31.Functional.SSANativeTopologyCheck
open S31.Functional.SSANamedExecution (laneValue)

def sourceBytes : List Nat := [
    99, 105, 114, 99, 117, 105, 116, 32, 101, 97, 114, 108, 121, 95, 111, 117,
    116, 112, 117, 116, 40, 112, 117, 98, 108, 105, 99, 32, 120, 58, 32, 91,
    109, 51, 49, 59, 32, 52, 93, 41, 32, 45, 62, 32, 112, 117, 98, 108,
    105, 99, 32, 91, 109, 51, 49, 59, 32, 52, 93, 32, 123, 10, 32, 32,
    108, 101, 116, 32, 97, 32, 61, 32, 120, 32, 46, 42, 32, 120, 59, 10,
    32, 32, 108, 101, 116, 32, 98, 32, 61, 32, 120, 32, 43, 32, 97, 59,
    10, 32, 32, 108, 101, 116, 32, 99, 32, 61, 32, 97, 32, 46, 42, 32,
    98, 59, 10, 32, 32, 97, 10, 125, 10
  ]
-- Informational digest from the outer package checker; Lean does not hash sourceBytes.
def sourceSha256 : String := "d382cee3a72ba2d22becf0c579580f97077e78e4cc7949f1e71c2800b42887be"
def changedSourceBytes : List Nat := [
    99, 105, 114, 99, 117, 105, 116, 32, 101, 97, 114, 108, 121, 95, 111, 117,
    116, 112, 117, 116, 40, 112, 117, 98, 108, 105, 99, 32, 120, 58, 32, 91,
    109, 51, 49, 59, 32, 52, 93, 41, 32, 45, 62, 32, 112, 117, 98, 108,
    105, 99, 32, 91, 109, 51, 49, 59, 32, 52, 93, 32, 123, 10, 32, 32,
    108, 101, 116, 32, 97, 32, 61, 32, 120, 32, 43, 32, 32, 120, 59, 10,
    32, 32, 108, 101, 116, 32, 98, 32, 61, 32, 120, 32, 43, 32, 97, 59,
    10, 32, 32, 108, 101, 116, 32, 99, 32, 61, 32, 97, 32, 46, 42, 32,
    98, 59, 10, 32, 32, 97, 10, 125, 10
  ]
def normalizedBytes : List Nat := [
    123, 10, 32, 32, 34, 97, 115, 115, 101, 114, 116, 105, 111, 110, 115, 34,
    58, 32, 91, 93, 44, 10, 32, 32, 34, 105, 110, 112, 117, 116, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 107, 105, 110, 100, 34, 58, 32, 34, 109, 51, 49, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 108, 101, 110, 103, 116, 104, 34, 58, 32, 52,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 120, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 118, 105, 115, 105,
    98, 105, 108, 105, 116, 121, 34, 58, 32, 34, 112, 117, 98, 108, 105, 99,
    34, 10, 32, 32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    110, 97, 109, 101, 34, 58, 32, 34, 101, 97, 114, 108, 121, 95, 111, 117,
    116, 112, 117, 116, 34, 44, 10, 32, 32, 34, 110, 111, 100, 101, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 108, 104, 115, 34, 58, 32, 34, 120, 34, 44, 10, 32, 32, 32, 32,
    32, 32, 34, 110, 97, 109, 101, 34, 58, 32, 34, 97, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 111, 112, 34, 58, 32, 34, 109, 117, 108, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 114, 104, 115, 34, 58, 32, 34,
    120, 34, 10, 32, 32, 32, 32, 125, 44, 10, 32, 32, 32, 32, 123, 10,
    32, 32, 32, 32, 32, 32, 34, 108, 104, 115, 34, 58, 32, 34, 120, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 98, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111, 112, 34, 58,
    32, 34, 97, 100, 100, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 114,
    104, 115, 34, 58, 32, 34, 97, 34, 10, 32, 32, 32, 32, 125, 44, 10,
    32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 34, 108, 104, 115,
    34, 58, 32, 34, 97, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 110,
    97, 109, 101, 34, 58, 32, 34, 99, 34, 44, 10, 32, 32, 32, 32, 32,
    32, 34, 111, 112, 34, 58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32,
    32, 32, 32, 32, 34, 114, 104, 115, 34, 58, 32, 34, 98, 34, 10, 32,
    32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34, 112, 117, 98,
    108, 105, 99, 95, 111, 117, 116, 112, 117, 116, 115, 34, 58, 32, 91, 10,
    32, 32, 32, 32, 34, 97, 34, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    118, 101, 114, 115, 105, 111, 110, 34, 58, 32, 49, 10, 125, 10
  ]
-- Informational digest from the outer package checker; Lean does not hash normalizedBytes.
def normalizedSha256 : String := "93bd19fc72c1e4526ad8bfe788f506bfea4c1787114df6e119dd95760efd888f"
def changedNormalizedOpcodeBytes : List Nat := [
    123, 10, 32, 32, 34, 97, 115, 115, 101, 114, 116, 105, 111, 110, 115, 34,
    58, 32, 91, 93, 44, 10, 32, 32, 34, 105, 110, 112, 117, 116, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 107, 105, 110, 100, 34, 58, 32, 34, 109, 51, 49, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 108, 101, 110, 103, 116, 104, 34, 58, 32, 52,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 120, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 118, 105, 115, 105,
    98, 105, 108, 105, 116, 121, 34, 58, 32, 34, 112, 117, 98, 108, 105, 99,
    34, 10, 32, 32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    110, 97, 109, 101, 34, 58, 32, 34, 101, 97, 114, 108, 121, 95, 111, 117,
    116, 112, 117, 116, 34, 44, 10, 32, 32, 34, 110, 111, 100, 101, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 108, 104, 115, 34, 58, 32, 34, 120, 34, 44, 10, 32, 32, 32, 32,
    32, 32, 34, 110, 97, 109, 101, 34, 58, 32, 34, 97, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 111, 112, 34, 58, 32, 34, 97, 100, 100, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 114, 104, 115, 34, 58, 32, 34,
    120, 34, 10, 32, 32, 32, 32, 125, 44, 10, 32, 32, 32, 32, 123, 10,
    32, 32, 32, 32, 32, 32, 34, 108, 104, 115, 34, 58, 32, 34, 120, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 98, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111, 112, 34, 58,
    32, 34, 97, 100, 100, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 114,
    104, 115, 34, 58, 32, 34, 97, 34, 10, 32, 32, 32, 32, 125, 44, 10,
    32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 34, 108, 104, 115,
    34, 58, 32, 34, 97, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 110,
    97, 109, 101, 34, 58, 32, 34, 99, 34, 44, 10, 32, 32, 32, 32, 32,
    32, 34, 111, 112, 34, 58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32,
    32, 32, 32, 32, 34, 114, 104, 115, 34, 58, 32, 34, 98, 34, 10, 32,
    32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34, 112, 117, 98,
    108, 105, 99, 95, 111, 117, 116, 112, 117, 116, 115, 34, 58, 32, 91, 10,
    32, 32, 32, 32, 34, 97, 34, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    118, 101, 114, 115, 105, 111, 110, 34, 58, 32, 49, 10, 125, 10
  ]
def changedNormalizedOutputBytes : List Nat := [
    123, 10, 32, 32, 34, 97, 115, 115, 101, 114, 116, 105, 111, 110, 115, 34,
    58, 32, 91, 93, 44, 10, 32, 32, 34, 105, 110, 112, 117, 116, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 107, 105, 110, 100, 34, 58, 32, 34, 109, 51, 49, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 108, 101, 110, 103, 116, 104, 34, 58, 32, 52,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 120, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 118, 105, 115, 105,
    98, 105, 108, 105, 116, 121, 34, 58, 32, 34, 112, 117, 98, 108, 105, 99,
    34, 10, 32, 32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    110, 97, 109, 101, 34, 58, 32, 34, 101, 97, 114, 108, 121, 95, 111, 117,
    116, 112, 117, 116, 34, 44, 10, 32, 32, 34, 110, 111, 100, 101, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 108, 104, 115, 34, 58, 32, 34, 120, 34, 44, 10, 32, 32, 32, 32,
    32, 32, 34, 110, 97, 109, 101, 34, 58, 32, 34, 97, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 111, 112, 34, 58, 32, 34, 109, 117, 108, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 114, 104, 115, 34, 58, 32, 34,
    120, 34, 10, 32, 32, 32, 32, 125, 44, 10, 32, 32, 32, 32, 123, 10,
    32, 32, 32, 32, 32, 32, 34, 108, 104, 115, 34, 58, 32, 34, 120, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 98, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111, 112, 34, 58,
    32, 34, 97, 100, 100, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 114,
    104, 115, 34, 58, 32, 34, 97, 34, 10, 32, 32, 32, 32, 125, 44, 10,
    32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 34, 108, 104, 115,
    34, 58, 32, 34, 97, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 110,
    97, 109, 101, 34, 58, 32, 34, 99, 34, 44, 10, 32, 32, 32, 32, 32,
    32, 34, 111, 112, 34, 58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32,
    32, 32, 32, 32, 34, 114, 104, 115, 34, 58, 32, 34, 98, 34, 10, 32,
    32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34, 112, 117, 98,
    108, 105, 99, 95, 111, 117, 116, 112, 117, 116, 115, 34, 58, 32, 91, 10,
    32, 32, 32, 32, 34, 122, 34, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    118, 101, 114, 115, 105, 111, 110, 34, 58, 32, 49, 10, 125, 10
  ]

def source : Source 1 :=
  (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.add (.var ⟨1, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.mul (.var ⟨1, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨2, by decide⟩))))

def certificate : Certificate :=
  { instructions := [
      { id := 1, lhs := 0, rhs := 0, multiply := true },
      { id := 2, lhs := 0, rhs := 1, multiply := false },
      { id := 3, lhs := 1, rhs := 2, multiply := true }],
    output := 1 }

-- This Program is rendered from the captured normalized JSON, while the
-- names below are independently compared to Lean's parse of sourceBytes.
def programName : String := "early_output"
def wireNames : List String := ["x", "a", "b", "c"]
def normalizedProgram : S31.Program :=
  { version := 1, name := "early_output", inputs := [{ name := "x", shape := ⟨.m31, 4⟩, visibility := .«public» }], nodes := [{ name := "a", op := .mul, lhs := some "x", rhs := some "x" }, { name := "b", op := .add, lhs := some "x", rhs := some "a" }, { name := "c", op := .mul, lhs := some "a", rhs := some "b" }], assertions := [], outputs := ["a"] }
def changedOpcodeProgram : S31.Program :=
  { version := 1, name := "early_output", inputs := [{ name := "x", shape := ⟨.m31, 4⟩, visibility := .«public» }], nodes := [{ name := "a", op := .add, lhs := some "x", rhs := some "x" }, { name := "b", op := .add, lhs := some "x", rhs := some "a" }, { name := "c", op := .mul, lhs := some "a", rhs := some "b" }], assertions := [], outputs := ["a"] }

def observedRows : List NativeSourceRow :=
  [
    { circuitRow := 6, traceRow := 502, multiply := true, in0 := 22, in1 := 22, out := 23 },
    { circuitRow := 7, traceRow := 3, multiply := false, in0 := 22, in1 := 23, out := 24 },
    { circuitRow := 8, traceRow := 503, multiply := true, in0 := 23, in1 := 24, out := 25 }
  ]

-- Physical source wire 0 is packed at circuit address 22. This projection
-- preserves the observed gate order and operation flags while renumbering
-- physical source addresses to the logical SSA wire IDs.
def projectedGates : List Gate :=
  observedRows.map (fun row =>
    { in0 := row.in0 - 22, in1 := row.in1 - 22,
       out := row.out - 22, multiply := row.multiply })
def changedOpcodeGates : List Gate :=
  projectedGates.modifyHead (fun gate => { gate with multiply := !gate.multiply })

def observedColumnCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 22, in1 := 22, out := 23, mults := 6 },
    { traceRow := 3, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 23, out := 24, mults := 1 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 24, out := 25, mults := 0 }
  ]
def changedSelectorCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 22, out := 23, mults := 6 },
    { traceRow := 3, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 23, out := 24, mults := 1 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 24, out := 25, mults := 0 }
  ]
def changedColumnAddressCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 22, in1 := 23, out := 23, mults := 6 },
    { traceRow := 3, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 23, out := 24, mults := 1 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 24, out := 25, mults := 0 }
  ]
def changedTraceRowCells : List ColumnCell :=
  [
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 24, out := 25, mults := 0 },
    { traceRow := 3, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 23, out := 24, mults := 1 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 24, out := 25, mults := 0 }
  ]
def changedMultiplicityCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 22, in1 := 22, out := 23, mults := 7 },
    { traceRow := 3, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 23, out := 24, mults := 1 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 24, out := 25, mults := 0 }
  ]

def observedOutputCells : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 1, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskSelector : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 23, in1 := 1, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskSource : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 1, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskRow : List ColumnCell :=
  [
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskMultiplicity : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 1, out := 26, mults := 2 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskBasis : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 1, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputInverseBasis : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 1, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 29, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 7, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputCopyAddress : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 1, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 15, out := 27, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 2, out := 30, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 16, out := 33, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 27, in1 := 28, out := 29, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 30, in1 := 31, out := 32, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 33, in1 := 34, out := 35, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 26, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 29, in1 := 0, out := 8, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 32, in1 := 0, out := 9, mults := 1 },
    { traceRow := 11, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 35, in1 := 0, out := 10, mults := 1 }
  ]
def observedPublicAddresses : List Nat := [2, 3, 4, 5, 6, 7, 8, 9, 10]
def changedPublicAddressOrder : List Nat := [2, 3, 4, 5, 6, 8, 7, 9, 10]

def observedInputCells : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 3 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 15, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 3, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 11, in1 := 1, out := 11, mults := 3 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]
def changedPackOperand : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 3 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 15, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 3, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 11, in1 := 1, out := 11, mults := 3 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]
def changedPackMultiplicity : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 4 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 15, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 3, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 11, in1 := 1, out := 11, mults := 3 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]
def changedPackBasis : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 3 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 3, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 11, in1 := 1, out := 11, mults := 3 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]
def changedInputCopyAddress : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 3 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 15, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 4, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 11, in1 := 1, out := 11, mults := 3 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]
def changedInputSelfSelector : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 3 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 15, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 3, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 1, out := 11, mults := 3 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]
def changedInputSelfMultiplicity : List ColumnCell :=
  [
    { traceRow := 0, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 17, out := 18, mults := 1 },
    { traceRow := 1, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 18, in1 := 19, out := 20, mults := 1 },
    { traceRow := 2, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 20, in1 := 21, out := 22, mults := 3 },
    { traceRow := 475, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 15, in1 := 12, out := 17, mults := 1 },
    { traceRow := 476, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 2, in1 := 13, out := 19, mults := 1 },
    { traceRow := 477, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 16, in1 := 14, out := 21, mults := 1 },
    { traceRow := 4, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 11, in1 := 0, out := 3, mults := 1 },
    { traceRow := 5, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 12, in1 := 0, out := 4, mults := 1 },
    { traceRow := 6, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 13, in1 := 0, out := 5, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 14, in1 := 0, out := 6, mults := 1 },
    { traceRow := 508, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 11, in1 := 1, out := 11, mults := 4 },
    { traceRow := 509, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 12, in1 := 1, out := 12, mults := 3 },
    { traceRow := 510, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 13, in1 := 1, out := 13, mults := 3 },
    { traceRow := 511, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 14, in1 := 1, out := 14, mults := 3 }
  ]

def observedAddRows : Nat := 474
def observedGateRows : Nat := 512
def observedVariables : Nat := 512

theorem source_byte_count : sourceBytes.length = 121 := by decide
theorem source_digest_length : sourceSha256.length = 64 := by decide
theorem bytes_parse_to_certificate :
    (parseBytes sourceBytes).map Parsed.certificate = some certificate := by decide
theorem bytes_parse_public_names :
    (parseBytes sourceBytes).map
      (fun p => (p.circuitName, p.inputName, p.outputName)) =
      some (token "early_output", token "x", token "a") := by decide
theorem bytes_parse_all_wire_names :
    (parseBytes sourceBytes).map Parsed.wireNames =
      some [token "x", token "a", token "b", token "c"] := by decide
theorem normalized_bytes_check :
    checkRelation sourceBytes normalizedBytes = some certificate := by decide
theorem changed_normalized_opcode_rejected :
    checkRelation sourceBytes changedNormalizedOpcodeBytes = none := by decide
theorem changed_normalized_public_output_rejected :
    checkRelation sourceBytes changedNormalizedOutputBytes = none := by decide
theorem changed_bytes_change_certificate :
    (parseBytes changedSourceBytes).map Parsed.certificate ≠
      some certificate := by decide
theorem source_ssa_checked : check source certificate = some () := by decide
theorem deterministic_emitter_matches : compile source = certificate := by decide
theorem source_native_rows_match :
    observedRows = expectedRows certificate observedAddRows := by decide
theorem named_program_source_rows_checked :
    checkNamedSourceRows source certificate programName wireNames
      normalizedProgram projectedGates =
      some (List.range (certificate.instructions.length + 1)) := by decide
theorem changed_named_opcode_rejected :
    checkNamedSourceRows source certificate programName wireNames
      changedOpcodeProgram projectedGates = none := by decide
theorem changed_projected_gate_rejected :
    checkNamedSourceRows source certificate programName wireNames
      normalizedProgram changedOpcodeGates = none := by decide
theorem observed_source_columns_match :
    observedColumnCells = expectedCells certificate observedAddRows := by decide
theorem changed_selector_cell_rejected :
    changedSelectorCells ≠ expectedCells certificate observedAddRows := by decide
theorem changed_column_address_cell_rejected :
    changedColumnAddressCells ≠ expectedCells certificate observedAddRows := by decide
theorem changed_trace_row_cell_rejected :
    changedTraceRowCells ≠ expectedCells certificate observedAddRows := by decide
theorem changed_multiplicity_cell_rejected :
    changedMultiplicityCells ≠ expectedCells certificate observedAddRows := by decide
theorem observed_output_cells_match :
    observedOutputCells = expectedOutputCells certificate observedAddRows := by decide
theorem selected_source_output_use_count :
    sourceUses certificate certificate.output = 6 := by decide
theorem changed_output_mask_selector_rejected :
    changedOutputMaskSelector ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_source_rejected :
    changedOutputMaskSource ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_row_rejected :
    changedOutputMaskRow ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_multiplicity_rejected :
    changedOutputMaskMultiplicity ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_basis_rejected :
    changedOutputMaskBasis ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_inverse_basis_rejected :
    changedOutputInverseBasis ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_copy_address_rejected :
    changedOutputCopyAddress ≠ expectedOutputCells certificate observedAddRows := by decide
theorem observed_public_addresses_match :
    observedPublicAddresses = expectedPublicAddresses := by decide
theorem changed_public_address_order_rejected :
    changedPublicAddressOrder ≠ expectedPublicAddresses := by decide
theorem observed_input_cells_match :
    observedInputCells = expectedInputCells certificate observedAddRows := by decide
theorem source_input_use_count : sourceInputUses certificate = 3 := by decide
theorem changed_pack_operand_rejected :
    changedPackOperand ≠ expectedInputCells certificate observedAddRows := by decide
theorem changed_pack_multiplicity_rejected :
    changedPackMultiplicity ≠ expectedInputCells certificate observedAddRows := by decide
theorem changed_pack_basis_rejected :
    changedPackBasis ≠ expectedInputCells certificate observedAddRows := by decide
theorem changed_input_copy_address_rejected :
    changedInputCopyAddress ≠ expectedInputCells certificate observedAddRows := by decide
theorem changed_input_self_selector_rejected :
    changedInputSelfSelector ≠ expectedInputCells certificate observedAddRows := by decide
theorem changed_input_self_multiplicity_rejected :
    changedInputSelfMultiplicity ≠ expectedInputCells certificate observedAddRows := by decide
theorem complete_native_shape :
    observedGateRows = 512 ∧ observedVariables = 512 := by decide

def changedSource : Source 1 :=
  (.letValue (.add (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.add (.var ⟨1, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.mul (.var ⟨1, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨2, by decide⟩))))

def changedOpcode : Certificate :=
  { instructions := [
      { id := 1, lhs := 0, rhs := 0, multiply := false },
      { id := 2, lhs := 0, rhs := 1, multiply := false },
      { id := 3, lhs := 1, rhs := 2, multiply := true }],
    output := 1 }

theorem changed_bytes_parse_changed_opcode :
    (parseBytes changedSourceBytes).map Parsed.certificate =
      some changedOpcode := by decide

def changedAddressRows : List NativeSourceRow :=
  [
    { circuitRow := 6, traceRow := 502, multiply := true, in0 := 22, in1 := 23, out := 23 },
    { circuitRow := 7, traceRow := 3, multiply := false, in0 := 22, in1 := 23, out := 24 },
    { circuitRow := 8, traceRow := 503, multiply := true, in0 := 23, in1 := 24, out := 25 }
  ]

theorem changed_source_rejected : check changedSource certificate = none := by decide
theorem changed_opcode_rejected : check source changedOpcode = none := by decide
theorem changed_address_rejected :
    changedAddressRows ≠ expectedRows certificate observedAddRows := by decide

/-- Source semantics for every four-lane input follow from the concrete
certificate check. The native-row premise remains a package-checker output,
and lookup/PCS soundness remains outside this theorem. -/
theorem checked_instance_sound (input : Lanes) :
    executeNormalized certificate input =
      some (source.value (fun _ => input)) :=
  (checked_rows_source_sound source certificate input observedRows
    observedAddRows source_ssa_checked source_native_rows_match).2

/-- The same result now starts from the actual embedded source bytes and
requires exact equality with the embedded canonical normalized JSON bytes.
Python's emitted Lean source term is not a premise of this theorem. -/
theorem checked_bytes_sound (input : Lanes) :
    executeNormalized certificate input = denotation sourceBytes input :=
  checked_relation_sound sourceBytes normalizedBytes certificate input
    normalized_bytes_check

/-- The captured normalized JSON runs through the actual named evaluator.
The admission test checks the package before rendering these constants;
Lean's byte and structural checks bind this concrete generated instance. -/
theorem checked_named_environment (assignment : S31.Assignment)
    (input : Lanes)
    (hprivate : assignment.privateInputs = [])
    (hinput : S31.assigned assignment.publicInputs (nameAt wireNames 0)
      ⟨.m31, 4⟩ = .ok (laneValue input)) :
    ∃ env,
      normalizedProgram.environment assignment = .ok env ∧
      S31.lookup env (nameAt wireNames certificate.output) =
        some (laneValue (source.value (fun _ => input))) :=
  checked_named_environment_sound wireNames source certificate programName
    normalizedProgram projectedGates
    (List.range (certificate.instructions.length + 1)) assignment input
    named_program_source_rows_checked hprivate hinput

/-- The named result is also the denotation of the captured source bytes,
because Lean separately checked the exact normalized JSON byte sequence. -/
theorem checked_named_source_bytes (assignment : S31.Assignment)
    (input : Lanes)
    (hprivate : assignment.privateInputs = [])
    (hinput : S31.assigned assignment.publicInputs (nameAt wireNames 0)
      ⟨.m31, 4⟩ = .ok (laneValue input)) :
    ∃ env,
      normalizedProgram.environment assignment = .ok env ∧
      (∃ value, S31.lookup env (nameAt wireNames certificate.output) =
        some (laneValue value) ∧ denotation sourceBytes input = some value) := by
  obtain ⟨env, henv, hlookup⟩ :=
    checked_named_environment assignment input hprivate hinput
  refine ⟨env, henv, source.value (fun _ => input), hlookup, ?_⟩
  rw [← checked_bytes_sound input]
  exact (checked_instance_sound input)

/-- Exact source selectors, addresses and output use counts from the exported
preprocessed cells agree with the SSA-derived row plan. The byte relation
premise is discharged for this concrete package instance. -/
theorem checked_column_cells_sound (input : Lanes) :
    observedColumnCells = expectedCells certificate observedAddRows ∧
      executeNormalized certificate input = denotation sourceBytes input :=
  checked_air_cells_sound sourceBytes normalizedBytes certificate input
    observedAddRows observedColumnCells normalized_bytes_check
    observed_source_columns_match

/-- The same exact byte admission also fixes the eleven exported public
output rows, subject to the package-to-Lean artifact premise. -/
theorem checked_output_cells_sound_instance (input : Lanes) :
    observedOutputCells = expectedOutputCells certificate observedAddRows ∧
      executeNormalized certificate input = denotation sourceBytes input :=
  checked_output_cells_sound sourceBytes normalizedBytes certificate input
    observedAddRows observedOutputCells normalized_bytes_check
    observed_output_cells_match

/-- Four public M31 words pack into the SSA input wire at address 22. The
value relation and lookup authentication remain native premises. -/
theorem checked_input_cells_sound_instance (input : Lanes) :
    observedInputCells = expectedInputCells certificate observedAddRows ∧
      executeNormalized certificate input = denotation sourceBytes input :=
  checked_input_cells_sound sourceBytes normalizedBytes certificate input
    observedAddRows observedInputCells normalized_bytes_check
    observed_input_cells_match

/-- Any complete accepted local arithmetic-row trace for these exact source
instructions has the source result, provided the row operands are the values
authenticated at their addressed prior wires. This does not discharge that
lookup premise or establish PCS binding of the observed row artifact. -/
theorem checked_instance_air_claim (input claimed : Lanes)
    (final : List Lanes)
    (hrows : AcceptsTrace [input] certificate.instructions final)
    (hclaim : final[certificate.output]? = some claimed) :
    observedRows = expectedRows certificate observedAddRows ∧
      observedColumnCells = expectedCells certificate observedAddRows ∧
      observedOutputCells = expectedOutputCells certificate observedAddRows ∧
      observedInputCells = expectedInputCells certificate observedAddRows ∧
      observedPublicAddresses = expectedPublicAddresses ∧
      denotation sourceBytes input = some claimed := by
  have hrun := accepted_trace_executes hrows
  have hbytes := checked_bytes_sound input
  rw [execute_normalized_eq_execute] at hbytes
  simp [execute, hrun, hclaim] at hbytes
  exact ⟨source_native_rows_match, observed_source_columns_match,
    observed_output_cells_match, observed_input_cells_match,
    observed_public_addresses_match, hbytes.symm⟩

end S31.Functional.GeneratedDirectGateMixedReturn
