-- Generated by scripts/export_s31_direct_gate_bridge.py from a checked package.
-- Source SHA-256: 2555767fb91b626f6ad959eb87bb2a83626f1aaacab3ad63179d966eeedfd1f6
import S31.Gadgets.Functional.SSADirectGateBridge
import S31.Gadgets.Functional.SSAAirRows
import S31.Gadgets.Functional.SSATextBytes
import S31.Gadgets.Functional.SSANormalizedBytes
import S31.Gadgets.Functional.SSAAirColumnCells
import S31.Gadgets.Functional.SSAOutputAirCells

set_option maxRecDepth 4096

namespace S31.Functional.GeneratedDirectGateBridge

open S31.Functional.SSACertificate
open S31.Functional.SSADirectGateBridge
open S31.Functional.SSAAirRows
open S31.Functional.SSATextBytes
open S31.Functional.SSANormalizedBytes
open S31.Functional.SSAAirColumnCells
open S31.Functional.SSAOutputAirCells

def sourceBytes : List Nat := [
    47, 47, 32, 70, 105, 114, 115, 116, 45, 111, 114, 100, 101, 114, 32, 114,
    101, 102, 101, 114, 101, 110, 99, 101, 32, 102, 111, 114, 32, 116, 104, 101,
    32, 104, 105, 103, 104, 101, 114, 45, 111, 114, 100, 101, 114, 32, 96, 102,
    117, 110, 99, 116, 105, 111, 110, 97, 108, 95, 115, 113, 117, 97, 114, 101,
    52, 46, 115, 51, 49, 96, 46, 10, 99, 105, 114, 99, 117, 105, 116, 32,
    102, 117, 110, 99, 116, 105, 111, 110, 97, 108, 95, 115, 113, 117, 97, 114,
    101, 52, 40, 112, 117, 98, 108, 105, 99, 32, 120, 58, 32, 91, 109, 51,
    49, 59, 32, 52, 93, 41, 32, 45, 62, 32, 112, 117, 98, 108, 105, 99,
    32, 91, 109, 51, 49, 59, 32, 52, 93, 32, 123, 10, 32, 32, 32, 32,
    108, 101, 116, 32, 111, 110, 99, 101, 32, 61, 32, 120, 32, 46, 42, 32,
    120, 59, 10, 32, 32, 32, 32, 108, 101, 116, 32, 114, 101, 115, 117, 108,
    116, 32, 61, 32, 111, 110, 99, 101, 32, 46, 42, 32, 111, 110, 99, 101,
    59, 10, 32, 32, 32, 32, 114, 101, 115, 117, 108, 116, 10, 125, 10
  ]
-- Informational digest from the outer package checker; Lean does not hash sourceBytes.
def sourceSha256 : String := "2555767fb91b626f6ad959eb87bb2a83626f1aaacab3ad63179d966eeedfd1f6"
def changedSourceBytes : List Nat := [
    47, 47, 32, 70, 105, 114, 115, 116, 45, 111, 114, 100, 101, 114, 32, 114,
    101, 102, 101, 114, 101, 110, 99, 101, 32, 102, 111, 114, 32, 116, 104, 101,
    32, 104, 105, 103, 104, 101, 114, 45, 111, 114, 100, 101, 114, 32, 96, 102,
    117, 110, 99, 116, 105, 111, 110, 97, 108, 95, 115, 113, 117, 97, 114, 101,
    52, 46, 115, 51, 49, 96, 46, 10, 99, 105, 114, 99, 117, 105, 116, 32,
    102, 117, 110, 99, 116, 105, 111, 110, 97, 108, 95, 115, 113, 117, 97, 114,
    101, 52, 40, 112, 117, 98, 108, 105, 99, 32, 120, 58, 32, 91, 109, 51,
    49, 59, 32, 52, 93, 41, 32, 45, 62, 32, 112, 117, 98, 108, 105, 99,
    32, 91, 109, 51, 49, 59, 32, 52, 93, 32, 123, 10, 32, 32, 32, 32,
    108, 101, 116, 32, 111, 110, 99, 101, 32, 61, 32, 120, 32, 43, 32, 32,
    120, 59, 10, 32, 32, 32, 32, 108, 101, 116, 32, 114, 101, 115, 117, 108,
    116, 32, 61, 32, 111, 110, 99, 101, 32, 46, 42, 32, 111, 110, 99, 101,
    59, 10, 32, 32, 32, 32, 114, 101, 115, 117, 108, 116, 10, 125, 10
  ]
def normalizedBytes : List Nat := [
    123, 10, 32, 32, 34, 97, 115, 115, 101, 114, 116, 105, 111, 110, 115, 34,
    58, 32, 91, 93, 44, 10, 32, 32, 34, 105, 110, 112, 117, 116, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 107, 105, 110, 100, 34, 58, 32, 34, 109, 51, 49, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 108, 101, 110, 103, 116, 104, 34, 58, 32, 52,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 120, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 118, 105, 115, 105,
    98, 105, 108, 105, 116, 121, 34, 58, 32, 34, 112, 117, 98, 108, 105, 99,
    34, 10, 32, 32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    110, 97, 109, 101, 34, 58, 32, 34, 102, 117, 110, 99, 116, 105, 111, 110,
    97, 108, 95, 115, 113, 117, 97, 114, 101, 52, 34, 44, 10, 32, 32, 34,
    110, 111, 100, 101, 115, 34, 58, 32, 91, 10, 32, 32, 32, 32, 123, 10,
    32, 32, 32, 32, 32, 32, 34, 108, 104, 115, 34, 58, 32, 34, 120, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 111, 110, 99, 101, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111,
    112, 34, 58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32, 32, 32, 32,
    32, 34, 114, 104, 115, 34, 58, 32, 34, 120, 34, 10, 32, 32, 32, 32,
    125, 44, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 34,
    108, 104, 115, 34, 58, 32, 34, 111, 110, 99, 101, 34, 44, 10, 32, 32,
    32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32, 34, 114, 101, 115,
    117, 108, 116, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111, 112, 34,
    58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34,
    114, 104, 115, 34, 58, 32, 34, 111, 110, 99, 101, 34, 10, 32, 32, 32,
    32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34, 112, 117, 98, 108, 105,
    99, 95, 111, 117, 116, 112, 117, 116, 115, 34, 58, 32, 91, 10, 32, 32,
    32, 32, 34, 114, 101, 115, 117, 108, 116, 34, 10, 32, 32, 93, 44, 10,
    32, 32, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 32, 49, 10, 125,
    10
  ]
-- Informational digest from the outer package checker; Lean does not hash normalizedBytes.
def normalizedSha256 : String := "b7d744dd89f487742f2b72cf71fa76c6c37c2f5b01b74b58befa24e8c749979c"
def changedNormalizedOpcodeBytes : List Nat := [
    123, 10, 32, 32, 34, 97, 115, 115, 101, 114, 116, 105, 111, 110, 115, 34,
    58, 32, 91, 93, 44, 10, 32, 32, 34, 105, 110, 112, 117, 116, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 107, 105, 110, 100, 34, 58, 32, 34, 109, 51, 49, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 108, 101, 110, 103, 116, 104, 34, 58, 32, 52,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 120, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 118, 105, 115, 105,
    98, 105, 108, 105, 116, 121, 34, 58, 32, 34, 112, 117, 98, 108, 105, 99,
    34, 10, 32, 32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    110, 97, 109, 101, 34, 58, 32, 34, 102, 117, 110, 99, 116, 105, 111, 110,
    97, 108, 95, 115, 113, 117, 97, 114, 101, 52, 34, 44, 10, 32, 32, 34,
    110, 111, 100, 101, 115, 34, 58, 32, 91, 10, 32, 32, 32, 32, 123, 10,
    32, 32, 32, 32, 32, 32, 34, 108, 104, 115, 34, 58, 32, 34, 120, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 111, 110, 99, 101, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111,
    112, 34, 58, 32, 34, 97, 100, 100, 34, 44, 10, 32, 32, 32, 32, 32,
    32, 34, 114, 104, 115, 34, 58, 32, 34, 120, 34, 10, 32, 32, 32, 32,
    125, 44, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 34,
    108, 104, 115, 34, 58, 32, 34, 111, 110, 99, 101, 34, 44, 10, 32, 32,
    32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32, 34, 114, 101, 115,
    117, 108, 116, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111, 112, 34,
    58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34,
    114, 104, 115, 34, 58, 32, 34, 111, 110, 99, 101, 34, 10, 32, 32, 32,
    32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34, 112, 117, 98, 108, 105,
    99, 95, 111, 117, 116, 112, 117, 116, 115, 34, 58, 32, 91, 10, 32, 32,
    32, 32, 34, 114, 101, 115, 117, 108, 116, 34, 10, 32, 32, 93, 44, 10,
    32, 32, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 32, 49, 10, 125,
    10
  ]
def changedNormalizedOutputBytes : List Nat := [
    123, 10, 32, 32, 34, 97, 115, 115, 101, 114, 116, 105, 111, 110, 115, 34,
    58, 32, 91, 93, 44, 10, 32, 32, 34, 105, 110, 112, 117, 116, 115, 34,
    58, 32, 91, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32,
    34, 107, 105, 110, 100, 34, 58, 32, 34, 109, 51, 49, 34, 44, 10, 32,
    32, 32, 32, 32, 32, 34, 108, 101, 110, 103, 116, 104, 34, 58, 32, 52,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 120, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 118, 105, 115, 105,
    98, 105, 108, 105, 116, 121, 34, 58, 32, 34, 112, 117, 98, 108, 105, 99,
    34, 10, 32, 32, 32, 32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34,
    110, 97, 109, 101, 34, 58, 32, 34, 102, 117, 110, 99, 116, 105, 111, 110,
    97, 108, 95, 115, 113, 117, 97, 114, 101, 52, 34, 44, 10, 32, 32, 34,
    110, 111, 100, 101, 115, 34, 58, 32, 91, 10, 32, 32, 32, 32, 123, 10,
    32, 32, 32, 32, 32, 32, 34, 108, 104, 115, 34, 58, 32, 34, 120, 34,
    44, 10, 32, 32, 32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32,
    34, 111, 110, 99, 101, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111,
    112, 34, 58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32, 32, 32, 32,
    32, 34, 114, 104, 115, 34, 58, 32, 34, 120, 34, 10, 32, 32, 32, 32,
    125, 44, 10, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 34,
    108, 104, 115, 34, 58, 32, 34, 111, 110, 99, 101, 34, 44, 10, 32, 32,
    32, 32, 32, 32, 34, 110, 97, 109, 101, 34, 58, 32, 34, 114, 101, 115,
    117, 108, 116, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34, 111, 112, 34,
    58, 32, 34, 109, 117, 108, 34, 44, 10, 32, 32, 32, 32, 32, 32, 34,
    114, 104, 115, 34, 58, 32, 34, 111, 110, 99, 101, 34, 10, 32, 32, 32,
    32, 125, 10, 32, 32, 93, 44, 10, 32, 32, 34, 112, 117, 98, 108, 105,
    99, 95, 111, 117, 116, 112, 117, 116, 115, 34, 58, 32, 91, 10, 32, 32,
    32, 32, 34, 122, 101, 115, 117, 108, 116, 34, 10, 32, 32, 93, 44, 10,
    32, 32, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 32, 49, 10, 125,
    10
  ]

def source : Source 1 :=
  (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨0, by decide⟩)))

def certificate : Certificate :=
  { instructions := [
      { id := 1, lhs := 0, rhs := 0, multiply := true },
      { id := 2, lhs := 1, rhs := 1, multiply := true }],
    output := 2 }

def observedRows : List NativeSourceRow :=
  [
    { circuitRow := 6, traceRow := 502, multiply := true, in0 := 22, in1 := 22, out := 23 },
    { circuitRow := 7, traceRow := 503, multiply := true, in0 := 23, in1 := 23, out := 24 }
  ]

def observedColumnCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 22, in1 := 22, out := 23, mults := 2 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 23, out := 24, mults := 4 }
  ]
def changedSelectorCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 22, in1 := 22, out := 23, mults := 2 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 23, out := 24, mults := 4 }
  ]
def changedColumnAddressCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 22, in1 := 23, out := 23, mults := 2 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 23, out := 24, mults := 4 }
  ]
def changedTraceRowCells : List ColumnCell :=
  [
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 23, out := 24, mults := 4 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 23, out := 24, mults := 4 }
  ]
def changedMultiplicityCells : List ColumnCell :=
  [
    { traceRow := 502, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 22, in1 := 22, out := 23, mults := 3 },
    { traceRow := 503, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 23, in1 := 23, out := 24, mults := 4 }
  ]

def observedOutputCells : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 1, out := 25, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskSelector : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 24, in1 := 1, out := 25, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskSource : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 25, in1 := 1, out := 25, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskRow : List ColumnCell :=
  [
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskMultiplicity : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 1, out := 25, mults := 2 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputMaskBasis : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 1, out := 25, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputInverseBasis : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 1, out := 25, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 28, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 7, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]
def changedOutputCopyAddress : List ColumnCell :=
  [
    { traceRow := 504, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 1, out := 25, mults := 1 },
    { traceRow := 505, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 15, out := 26, mults := 1 },
    { traceRow := 506, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 2, out := 29, mults := 1 },
    { traceRow := 507, addFlag := 0, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 1, in0 := 24, in1 := 16, out := 32, mults := 1 },
    { traceRow := 478, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 26, in1 := 27, out := 28, mults := 1 },
    { traceRow := 479, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 29, in1 := 30, out := 31, mults := 1 },
    { traceRow := 480, addFlag := 0, subFlag := 0, mulFlag := 1, pointwiseMulFlag := 0, in0 := 32, in1 := 33, out := 34, mults := 1 },
    { traceRow := 7, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 25, in1 := 0, out := 8, mults := 1 },
    { traceRow := 8, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 28, in1 := 0, out := 8, mults := 1 },
    { traceRow := 9, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 31, in1 := 0, out := 9, mults := 1 },
    { traceRow := 10, addFlag := 1, subFlag := 0, mulFlag := 0, pointwiseMulFlag := 0, in0 := 34, in1 := 0, out := 10, mults := 1 }
  ]

def observedAddRows : Nat := 474
def observedGateRows : Nat := 512
def observedVariables : Nat := 512

theorem source_byte_count : sourceBytes.length = 207 := by decide
theorem source_digest_length : sourceSha256.length = 64 := by decide
theorem bytes_parse_to_certificate :
    (parseBytes sourceBytes).map Parsed.certificate = some certificate := by decide
theorem bytes_parse_public_names :
    (parseBytes sourceBytes).map
      (fun p => (p.circuitName, p.inputName, p.outputName)) =
      some (token "functional_square4", token "x", token "result") := by decide
theorem normalized_bytes_check :
    checkRelation sourceBytes normalizedBytes = some certificate := by decide
theorem changed_normalized_opcode_rejected :
    checkRelation sourceBytes changedNormalizedOpcodeBytes = none := by decide
theorem changed_normalized_public_output_rejected :
    checkRelation sourceBytes changedNormalizedOutputBytes = none := by decide
theorem changed_bytes_change_certificate :
    (parseBytes changedSourceBytes).map Parsed.certificate ≠
      some certificate := by decide
theorem source_ssa_checked : check source certificate = some () := by decide
theorem deterministic_emitter_matches : compile source = certificate := by decide
theorem source_native_rows_match :
    observedRows = expectedRows certificate observedAddRows := by decide
theorem observed_source_columns_match :
    observedColumnCells = expectedCells certificate observedAddRows := by decide
theorem changed_selector_cell_rejected :
    changedSelectorCells ≠ expectedCells certificate observedAddRows := by decide
theorem changed_column_address_cell_rejected :
    changedColumnAddressCells ≠ expectedCells certificate observedAddRows := by decide
theorem changed_trace_row_cell_rejected :
    changedTraceRowCells ≠ expectedCells certificate observedAddRows := by decide
theorem changed_multiplicity_cell_rejected :
    changedMultiplicityCells ≠ expectedCells certificate observedAddRows := by decide
theorem observed_output_cells_match :
    observedOutputCells = expectedOutputCells certificate observedAddRows := by decide
theorem selected_source_output_has_four_mask_reads :
    sourceUses certificate certificate.output = 4 := by decide
theorem changed_output_mask_selector_rejected :
    changedOutputMaskSelector ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_source_rejected :
    changedOutputMaskSource ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_row_rejected :
    changedOutputMaskRow ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_multiplicity_rejected :
    changedOutputMaskMultiplicity ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_mask_basis_rejected :
    changedOutputMaskBasis ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_inverse_basis_rejected :
    changedOutputInverseBasis ≠ expectedOutputCells certificate observedAddRows := by decide
theorem changed_output_copy_address_rejected :
    changedOutputCopyAddress ≠ expectedOutputCells certificate observedAddRows := by decide
theorem complete_native_shape :
    observedGateRows = 512 ∧ observedVariables = 512 := by decide

def changedSource : Source 1 :=
  (.letValue (.add (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.letValue (.mul (.var ⟨0, by decide⟩) (.var ⟨0, by decide⟩)) (.var ⟨0, by decide⟩)))

def changedOpcode : Certificate :=
  { instructions := [
      { id := 1, lhs := 0, rhs := 0, multiply := false },
      { id := 2, lhs := 1, rhs := 1, multiply := true }],
    output := 2 }

theorem changed_bytes_parse_changed_opcode :
    (parseBytes changedSourceBytes).map Parsed.certificate =
      some changedOpcode := by decide

def changedAddressRows : List NativeSourceRow :=
  [
    { circuitRow := 6, traceRow := 502, multiply := true, in0 := 22, in1 := 23, out := 23 },
    { circuitRow := 7, traceRow := 503, multiply := true, in0 := 23, in1 := 23, out := 24 }
  ]

theorem changed_source_rejected : check changedSource certificate = none := by decide
theorem changed_opcode_rejected : check source changedOpcode = none := by decide
theorem changed_address_rejected :
    changedAddressRows ≠ expectedRows certificate observedAddRows := by decide

/-- Source semantics for every four-lane input follow from the concrete
certificate check. The native-row premise remains a package-checker output,
and lookup/PCS soundness remains outside this theorem. -/
theorem checked_instance_sound (input : Lanes) :
    executeNormalized certificate input =
      some (source.value (fun _ => input)) :=
  (checked_rows_source_sound source certificate input observedRows
    observedAddRows source_ssa_checked source_native_rows_match).2

/-- The same result now starts from the actual embedded source bytes and
requires exact equality with the embedded canonical normalized JSON bytes.
Python's emitted Lean source term is not a premise of this theorem. -/
theorem checked_bytes_sound (input : Lanes) :
    executeNormalized certificate input = denotation sourceBytes input :=
  checked_relation_sound sourceBytes normalizedBytes certificate input
    normalized_bytes_check

/-- Exact source selectors, addresses and output use counts from the exported
preprocessed cells agree with the SSA-derived row plan. The byte relation
premise is discharged for this concrete package instance. -/
theorem checked_column_cells_sound (input : Lanes) :
    observedColumnCells = expectedCells certificate observedAddRows ∧
      executeNormalized certificate input = denotation sourceBytes input :=
  checked_air_cells_sound sourceBytes normalizedBytes certificate input
    observedAddRows observedColumnCells normalized_bytes_check
    observed_source_columns_match

/-- The same exact byte admission also fixes the eleven exported public
output rows, subject to the package-to-Lean artifact premise. -/
theorem checked_output_cells_sound_instance (input : Lanes) :
    observedOutputCells = expectedOutputCells certificate observedAddRows ∧
      executeNormalized certificate input = denotation sourceBytes input :=
  checked_output_cells_sound sourceBytes normalizedBytes certificate input
    observedAddRows observedOutputCells normalized_bytes_check
    observed_output_cells_match

/-- Any complete accepted local arithmetic-row trace for these exact source
instructions has the source result, provided the row operands are the values
authenticated at their addressed prior wires. This does not discharge that
lookup premise or establish PCS binding of the observed row artifact. -/
theorem checked_instance_air_claim (input claimed : Lanes)
    (final : List Lanes)
    (hrows : AcceptsTrace [input] certificate.instructions final)
    (hclaim : final[certificate.output]? = some claimed) :
    observedRows = expectedRows certificate observedAddRows ∧
      observedColumnCells = expectedCells certificate observedAddRows ∧
      observedOutputCells = expectedOutputCells certificate observedAddRows ∧
      denotation sourceBytes input = some claimed := by
  have hrun := accepted_trace_executes hrows
  have hbytes := checked_bytes_sound input
  rw [execute_normalized_eq_execute] at hbytes
  simp [execute, hrun, hclaim] at hbytes
  exact ⟨source_native_rows_match, observed_source_columns_match,
    observed_output_cells_match, hbytes.symm⟩

end S31.Functional.GeneratedDirectGateBridge
