import S31.Gadgets.Functional.TextSquare4Air

/-! Generated by the production S31 direct circuit compiler. -/
namespace S31.Functional.TextSquare4Native

structure Gate where
  input0 : Nat
  input1 : Nat
  output : Nat
deriving DecidableEq, Repr

def first : Gate := ⟨22, 22, 23⟩
def second : Gate := ⟨23, 23, 24⟩
def nodeRowSpans : List (Nat × Nat) := [(6, 7), (7, 8)]

end S31.Functional.TextSquare4Native
