import S31.Semantics.Program

/-! Generated by the S31 text compiler from functional_square4.s31. -/
namespace S31.Functional.TextSquare4

def compiled : S31.Program := {
  version := 1,
  name := "functional_square4",
  inputs := [{ name := "x", shape := ⟨.m31, 4⟩, visibility := .«public» }],
  nodes := [
    { name := "_s31_i1_0", op := .mul, lhs := some "x", rhs := some "x" },
    { name := "result", op := .mul, lhs := some "_s31_i1_0", rhs := some "_s31_i1_0" }
  ],
  assertions := [],
  outputs := ["result"]
}

end S31.Functional.TextSquare4
