import S31.Gadgets.Functional.TextSquare4Air

/-! Generated by the production S31 direct circuit compiler. -/
namespace S31.Functional.TextSquare4Native

structure Gate where
  input0 : Nat
  input1 : Nat
  output : Nat
deriving DecidableEq, Repr, Inhabited

def first : Gate := ⟨22, 22, 23⟩
def second : Gate := ⟨23, 23, 24⟩
def nodeRowSpans : List (Nat × Nat) := [(6, 7), (7, 8)]
def declaredVarCount : Nat := 322
def declaredProducerAddresses : List Nat := List.range declaredVarCount
def arithmeticRowCount : Nat := 322
def paddedArithmeticRowCount : Nat := 512
def paddedDeclaredVarCount : Nat := 608
def permutationTermCount : Nat := 0
def mulRowStart : Nat := 475
def pointRowStart : Nat := 502
def inputWires : List Nat := [11, 12, 13, 14]
def inputBasisWires : List Nat := [15, 2, 16]
def activeArithmeticProducerAddresses : List Nat := [
  18, 20, 22, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 35, 36, 37,
  38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
  54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
  70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
  86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
  102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
  118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
  134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
  150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
  166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
  182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
  198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
  214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
  230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
  246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
  262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
  278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 291, 295, 297, 299,
  301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 15, 17, 19, 21, 28,
  31, 34, 2, 290, 292, 294, 296, 298, 300, 302, 304, 306, 33, 308, 310, 312,
  27, 16, 314, 316, 318, 320, 30, 23, 24, 25, 26, 29, 32, 11, 12, 13,
  14
]
def externalProducerAddresses : List Nat := []
def inputPackMul : List Gate := [⟨15, 12, 17⟩, ⟨2, 13, 19⟩, ⟨16, 14, 21⟩]
def inputPackAdd : List Gate := [⟨11, 17, 18⟩, ⟨18, 19, 20⟩, ⟨20, 21, 22⟩]

def zeroWire : Nat := 0
def inputBindingAdd : List Gate := [⟨11, 0, 3⟩, ⟨12, 0, 4⟩, ⟨13, 0, 5⟩, ⟨14, 0, 6⟩]
def outputUnpackPoint : List Gate := [⟨24, 1, 25⟩, ⟨24, 15, 26⟩, ⟨24, 2, 29⟩, ⟨24, 16, 32⟩]
def outputUnpackMul : List Gate := [⟨26, 27, 28⟩, ⟨29, 30, 31⟩, ⟨32, 33, 34⟩]
def outputBindingAdd : List Gate := [⟨25, 0, 7⟩, ⟨28, 0, 8⟩, ⟨31, 0, 9⟩, ⟨34, 0, 10⟩]
def publicInputWires : List Nat := [3, 4, 5, 6]
def publicOutputWires : List Nat := [7, 8, 9, 10]

end S31.Functional.TextSquare4Native
