"""Render independent QM31 vectors for the installed direct-Gate native evaluator.

The scalar opcode replay lives in the Python correspondence tests. This file
pins its results as literal Zig test data; the native test never calls Python.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src/frontends/s31/tests/python"))
from test_gate_bytecode_arithmetic import decoded_program, gate_program, replay_oods  # noqa: E402
from export_s31_direct_gate_evaluator_fixture import base, mul, scale  # noqa: E402

P = (1 << 31) - 1
EXPECTED_BUNDLE_SHA256 = "7b8022b09d84db371cc433aa0fcf132f7687f2720e05e4dc9a7650c575dc02c2"
BUNDLE = ROOT / "deps/stwo-zig/vectors/circuit/official/circuit_air.air_programs_v1.bin"
OUTPUT = ROOT / "deps/stwo-zig/src/frontends/cairo/witness/gate_oods_vectors.zig"


def sample(seed: int, group: int, index: int) -> tuple[int, int, int, int]:
    """Four genuinely nonbase QM31 coordinates, all below the M31 modulus."""
    return tuple((seed + group * 1009 + index * 101 + limb * 13) % P
                 for limb in range(4))


def vector(seed: int, program: object) -> tuple[tuple[tuple[int, ...], ...],
                                                tuple[tuple[int, ...], ...]]:
    fixed = tuple(sample(seed, 0, i) for i in range(8))
    main = tuple(sample(seed, 1, i) for i in range(12))
    current = tuple(sample(seed, 2, i) for i in range(8))
    previous = tuple(sample(seed, 3, i) for i in range(8))
    alpha, z, claimed = (sample(seed, group, 0) for group in (4, 5, 6))
    scaled = scale(claimed, pow(512, -1, P))
    power = base(1)
    params = []
    for _ in range(5):
        power = mul(power, alpha)
        params.append(power)
    params.extend((z, scaled))
    roots = replay_oods(program, fixed, main, current, previous, alpha, z, scaled)
    return tuple(params), roots


def render(bundle: bytes) -> str:
    digest = hashlib.sha256(bundle).hexdigest()
    if digest != EXPECTED_BUNDLE_SHA256:
        raise ValueError(f"installed evaluator bundle changed: {digest}")
    program = decoded_program(gate_program(bundle))
    if len(program[2]) != 11:
        raise ValueError("selected Gate root count changed")
    lines = [
        "// Generated by scripts/export_s31_native_gate_oods_vectors.py.",
        "// Independent Python scalar bytecode replay; native test consumes literals.",
        f'pub const bundle_sha256 = "{digest}";',
        "pub const Vector = struct {",
        "    seed: u32,",
        "    params: [7][4]u32,",
        "    roots: [11][4]u32,",
        "};",
        "pub const cases = [_]Vector{",
    ]
    for seed in (3, 211):
        params, roots = vector(seed, program)
        lines.extend(("    .{", f"        .seed = {seed},", "        .params = .{"))
        lines.extend(f"            .{{ {', '.join(map(str, words))} }}," for words in params)
        lines.extend(("        },", "        .roots = .{"))
        lines.extend(f"            .{{ {', '.join(map(str, words))} }}," for words in roots)
        lines.extend(("        },", "    },"))
    lines.extend(("};", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="reject a changed native fixture")
    args = parser.parse_args()
    rendered = render(BUNDLE.read_bytes())
    if args.check:
        if OUTPUT.read_text() != rendered:
            raise SystemExit("native Gate OODS fixture differs from independent scalar replay")
    else:
        OUTPUT.write_text(rendered)
