import S31.Gadgets.Air.LogUpInteraction

/-! Generated by symbolic execution of the native LogUp builder formulas. -/
namespace S31.Gadgets.Air.NativeLogUpAir
open S31.Gadgets.Air.GateChallenge
open S31.Gadgets.Air.LogUpInteraction

def combine (tuple : Fin 6 → GateSecure) (alpha z : GateSecure) : GateSecure :=
  (((((((((((tuple 5 * alpha) + tuple 4) * alpha) + tuple 3) * alpha) + tuple 2) * alpha) + tuple 1) * alpha) + tuple 0) - z)

def single (term : Term GateSecure) (diff : GateSecure) : GateSecure :=
  ((diff * term.denominator) - term.numerator)

def pair (left right : Term GateSecure) (diff : GateSecure) : GateSecure :=
  ((diff * (left.denominator * right.denominator)) - ((right.numerator * left.denominator) + (left.numerator * right.denominator)))

end S31.Gadgets.Air.NativeLogUpAir
