import S31.Gadgets.Air.NativeLogUpAir

/-! Generated by executing the native two- and three-term LogUp batch finalizer. -/
namespace S31.Gadgets.Air.NativeLogUpBatches
open S31.Gadgets.Air.GateChallenge
open S31.Gadgets.Air.LogUpInteraction

def basisI : GateSecure := ⟨⟨0, 1⟩, ⟨0, 0⟩⟩
def basisU : GateSecure := ⟨⟨0, 0⟩, ⟨1, 0⟩⟩
def basisIU : GateSecure := ⟨⟨0, 0⟩, ⟨0, 1⟩⟩

def threeTermAccumulator (a b c : Term GateSecure)
    (first prev last : Fin 4 → GateSecure)
    (rho claimed nInstances : GateSecure) : GateSecure :=
  ((((0 * rho) + (((((first 0 + (first 1 * basisI)) + (first 2 * basisU)) + (first 3 * basisIU)) * (a.denominator * b.denominator)) - ((b.numerator * a.denominator) + (a.numerator * b.denominator)))) * rho) + ((((((((last 0 + (last 1 * basisI)) + (last 2 * basisU)) + (last 3 * basisIU)) - (((prev 0 + (prev 1 * basisI)) + (prev 2 * basisU)) + (prev 3 * basisIU))) - (((first 0 + (first 1 * basisI)) + (first 2 * basisU)) + (first 3 * basisIU))) + (claimed * (nInstances)⁻¹)) * c.denominator) - c.numerator))

def threeTermWithPrefix (prior : GateSecure) (a b c : Term GateSecure)
    (first prev last : Fin 4 → GateSecure)
    (rho claimed nInstances : GateSecure) : GateSecure :=
  ((((prior * rho) + (((((first 0 + (first 1 * basisI)) + (first 2 * basisU)) + (first 3 * basisIU)) * (a.denominator * b.denominator)) - ((b.numerator * a.denominator) + (a.numerator * b.denominator)))) * rho) + ((((((((last 0 + (last 1 * basisI)) + (last 2 * basisU)) + (last 3 * basisIU)) - (((prev 0 + (prev 1 * basisI)) + (prev 2 * basisU)) + (prev 3 * basisIU))) - (((first 0 + (first 1 * basisI)) + (first 2 * basisU)) + (first 3 * basisIU))) + (claimed * (nInstances)⁻¹)) * c.denominator) - c.numerator))

def twoTermWithPrefix (prior : GateSecure) (a b : Term GateSecure)
    (prev last : Fin 4 → GateSecure)
    (rho claimed nInstances : GateSecure) : GateSecure :=
  ((prior * rho) + ((((((((last 0 + (last 1 * basisI)) + (last 2 * basisU)) + (last 3 * basisIU)) - (((prev 0 + (prev 1 * basisI)) + (prev 2 * basisU)) + (prev 3 * basisIU))) - 0) + (claimed * (nInstances)⁻¹)) * (a.denominator * b.denominator)) - ((b.numerator * a.denominator) + (a.numerator * b.denominator))))

end S31.Gadgets.Air.NativeLogUpBatches
