//! Extract the gate chain produced by the real S31 direct compiler for the
//! normalized functional_square4 program. The Python formal gate supplies
//! the IR freshly compiled from the `.s31` source on every run.
const std = @import("std");
const circuit = @import("stwo_circuit_frontend");
const s31 = @import("stwo_s31_prototype");

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);
    if (args.len != 2) return error.ExpectedNormalizedSourcePath;
    const source = try std.fs.cwd().readFileAlloc(allocator, args[1], 1 << 20);
    defer allocator.free(source);
    var parsed = try s31.relation.parseProgram(allocator, source);
    defer parsed.deinit();
    const program = parsed.value;
    if (!std.mem.eql(u8, program.name, "functional_square4") or
        program.inputs.len != 1 or program.nodes.len != 2 or
        program.assertions.len != 0 or program.public_outputs.len != 1 or
        program.inputs[0].kind != .m31 or program.inputs[0].length != 4 or
        program.inputs[0].visibility != .public or
        !std.mem.eql(u8, program.inputs[0].name, "x") or
        program.nodes[0].op != .mul or program.nodes[1].op != .mul or
        !std.mem.eql(u8, program.nodes[0].name, "_s31_i1_0") or
        !std.mem.eql(u8, program.nodes[1].name, "result") or
        !std.mem.eql(u8, program.public_outputs[0], "result"))
        return error.UnexpectedFunctionalProgram;

    var maps = s31.relation_compiler.Maps{};
    defer maps.deinit(allocator);
    var ctx = try s31.relation_compiler.compileDirectWithSpans(circuit.builder.NoValue, allocator, program, null, &maps, false);
    defer ctx.deinit();
    if (maps.nodes.items.len != 3) return error.UnexpectedCanonicalNodeCount;
    const first_span = maps.nodes.items[1];
    const second_span = maps.nodes.items[2];
    if (first_span.qm31_end != first_span.qm31_start + 1 or
        second_span.qm31_end != second_span.qm31_start + 1 or
        first_span.qm31_end != second_span.qm31_start)
        return error.UnexpectedArithmeticRowSpan;
    if (ctx.circuit.pointwise_mul.items.len < 2)
        return error.MissingPointwiseGates;
    const first = ctx.circuit.pointwise_mul.items[0];
    const second = ctx.circuit.pointwise_mul.items[1];
    if (first.in0 != first.in1 or second.in0 != second.in1 or
        second.in0 != first.out)
        return error.UnexpectedSquareGateChain;
    var input_packed_by_add = false;
    for (ctx.circuit.add.items) |gate| {
        if (gate.out == first.in0) input_packed_by_add = true;
    }
    if (!input_packed_by_add) return error.UnexpectedInputPacking;

    var buffer: [4096]u8 = undefined;
    var stdout = std.fs.File.stdout().writer(&buffer);
    const writer = &stdout.interface;
    try writer.writeAll("import S31.Gadgets.Functional.TextSquare4Air\n\n" ++
        "/-! Generated by the production S31 direct circuit compiler. -/\n" ++
        "namespace S31.Functional.TextSquare4Native\n\n" ++
        "structure Gate where\n  input0 : Nat\n  input1 : Nat\n  output : Nat\n" ++
        "deriving DecidableEq, Repr\n\n");
    try writer.print(
        "def first : Gate := ⟨{d}, {d}, {d}⟩\n" ++
            "def second : Gate := ⟨{d}, {d}, {d}⟩\n" ++
            "def nodeRowSpans : List (Nat × Nat) := [({d}, {d}), ({d}, {d})]\n\n",
        .{ first.in0, first.in1, first.out, second.in0, second.in1, second.out, first_span.qm31_start, first_span.qm31_end, second_span.qm31_start, second_span.qm31_end },
    );
    try writer.writeAll("end S31.Functional.TextSquare4Native\n");
    try stdout.interface.flush();
}
